name: Super-Linter

on: push

permissions: {}

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-linter
        uses: github/super-linter@v3 # x-release-please-version
        env:
          DEFAULT_BRANCH: master
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
